### PR TITLE
[ready] Add description, keywords, change titles

### PR DESCRIPTION
**Pull request by romkebon**
Some SEO stuff with @mildaskl

### CODE REVIEW

**Comment by romkebon** [comment]
@dkhgh can you check and merge this?

**Comment by dkhgh** [comment]
Do we also need a title for the login page?

**Comment by romkebon** [comment]
Yup, done.

**Comment by romkebon** [comment]
Wait, still have to fix dutch and german

**Comment by mildaskl** [comment]
Isa asked to wait for german. She wants to change the text.

**Comment by mildaskl** [comment]
Btw, Isa wants to change the text on the german page

**Comment by mildaskl** [comment]
Btw, Isa wants to change the text on the german page

**Comment by mildaskl** [comment]
Btw, Isa wants to change the text on the german page

**Comment by romkebon** [comment]
I know, just made sure there are no errors. Btw, you closed the pull request... :confused:

**Comment by dkhgh** [comment]
:-1:

**Comment by mildaskl** [comment]
Fuck. Sorry

**Pull request closed without merging**
