### PR TITLE
[ready] redirect trial request to the trial sign up

### PR DESCRIPTION
**Pull request by fatboypunk**
please merge after https://github.com/DefactoSoftware/LearningSpaces/pull/999

### CODE REVIEW

**Comment by fatboypunk** [comment]
This also needs to wait for https://github.com/DefactoSoftware/LearningSpaces/pull/992

After that we need to inform sales people 
* that a first mail was already sent to the owner
* an account has already been created

**Comment by fatboypunk** [comment]
This could be merged now

**Comment by fatboypunk** [comment]
Everything on LearningSpaces is done now, I think we can merge this one too :dancers: 
@DefactoSoftware/learningspaces

**Comment by jejote** [comment]
so do I register a new demo tenant and walk through the onboarding of the tenant owner myself, or do i sign up with the email of the client and have the client do it, and have them have admin-rights?

**Comment by fatboypunk** [comment]
So now when a trial is requested you won't have to do anything al the mails and setup to get started will be done in the app itself

**Comment by fatboypunk** [comment]
And you could add an tenant on staging to see how it works and which mails you'll get. Everything should work except for the trello mail (because it's staging)

**Pull request merged**
