### PR TITLE
[WIP] language selector in menu

### PR DESCRIPTION
**Pull request by matthijskuiper**
Addressing issue https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/3.
This is an attempt for the language selection option in the menu. It works but not sure if this is the best way/position to go for.
@dkhgh @romkebon ?

screen shot 2015-02-04 at 17 04 52

screen shot 2015-02-04 at 17 05 42

### CODE REVIEW

**Comment by dkhgh** [comment]
I like it but shouldn't log-in be the option that's most to the right?

**Comment by matthijskuiper** [comment]
I had the same thought, but I wanted to try this first. It's a secondary action and doesn't really fit in with the primary navigation.

**Comment by dkhgh** [comment]
LESGO?!?! \0/

**Comment by matthijskuiper** [comment]
It's (a)[live](http://www.learningspaces.io/) !!!!!

**Pull request merged**
