### PR TITLE
[READY] FAQ anchors with pageviews

### PR DESCRIPTION
**Pull request by sn3p**
Fixes https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/65

- [x] Update URL by adding `#hash-of-question-title-slug` when collapsing a question (if [history api](http://caniuse.com/#feat=history) is supported).
- [x] Making it possible to link and auto-collapse questions like `/faq/#hash-of-question-title-slug`.
- [x] Send GA pageview when collapsing a question.

Have to test this live because GA is not loaded/tracked in development.

### CODE REVIEW

**Comment by sn3p** [comment]
@fatboypunk kiek maar eem

**Comment by fatboypunk** [comment]
Love it, are we going to make the titles 'linkable' as well?

**Comment by sn3p** [comment]
They are

> Making it possible to link and auto-collapse questions like `/faq/#hash-of-question-title-slug`.

**Comment by fatboypunk** [comment]
Yeah those are only the questions i meant the  h1 product/getting started/etc

**Comment by sn3p** [comment]
Ah yes forgot about those. Added now.

**Comment by sn3p** [comment]
ah forgot about those. Added now.

**Comment by fatboypunk** [comment]
awesome!

**Pull request merged**
